name: Build and Push Docker Image

on:
  push:
    branches: [ $default-branch ]
    # Publish semver tags as releases.
    tags: [ '[0-9]+.[0-9]+.[0-9]+' ]

env:
  IMAGE_NAME: socks5-proxy

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME}}
          tags: |
            type=ref,event=tag
            type=semver,pattern={{version}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Verify published image
        run: |
          echo "The Docker image has been published to GitHub Container Registry."
          echo "Image tags: ${{ steps.meta.outputs.tags }}"
